ALTER SESSION SET CONTAINER       = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA  = ADMIN;
/
CREATE TABLE ADMIN.HO_LISTA_TOTEMANGOL (
  ID_TOTEM           NUMBER NOT NULL,
  IND_ESTADO         NUMBER,
  TXT_DESCRIPCION    VARCHAR2(512 BYTE),
  COD_EMPRESA        VARCHAR2(50 BYTE),
  IND_IP             VARCHAR2(50 BYTE),
  TXT_ID             VARCHAR2(50 BYTE),
  IND_PISO           NUMBER,
  TXT_LLAVE          VARCHAR2(50 BYTE),
  TXT_LOCATION       VARCHAR2(50 BYTE),
  IND_STATUS         NUMBER,
  TXT_OBSERVACIONES  VARCHAR2(512 BYTE),
  PC_MAC             VARCHAR2(50 BYTE),
  CONSTRAINT PK_ID_TOTEM PRIMARY KEY (ID_TOTEM)
);
COMMIT;
INSERT INTO ADMIN.HO_LISTA_TOTEMANGOL(ID_TOTEM,IND_ESTADO,TXT_DESCRIPCION,COD_EMPRESA,IND_IP,IND_PISO,TXT_LLAVE,TXT_LOCATION,IND_STATUS,TXT_OBSERVACIONES,PC_MAC) VALUES (1,1,'amitot-09-002','100','10.68.159.13',1,'INF001-U1','VERDE U01',1,'TEST','00:E0:4C:68:39:30');
INSERT INTO ADMIN.HO_LISTA_TOTEMANGOL(ID_TOTEM,IND_ESTADO,TXT_DESCRIPCION,COD_EMPRESA,IND_IP,IND_PISO,TXT_LLAVE,TXT_LOCATION,IND_STATUS,TXT_OBSERVACIONES,PC_MAC) VALUES (2,1,'amitot-09-001','100','10.69.74.123',1,'INF001-U2','VERDE U02',1,'FARMACIA','9CFCE87F1499');
INSERT INTO ADMIN.HO_LISTA_TOTEMANGOL(ID_TOTEM,IND_ESTADO,TXT_DESCRIPCION,COD_EMPRESA,IND_IP,IND_PISO,TXT_LLAVE,TXT_LOCATION,IND_STATUS,TXT_OBSERVACIONES,PC_MAC) VALUES (3,1,'amitot-09-002','100','10.69.74.125',1,'INF001-U3','VERDE U03',1,'FARMACIA','002B67383F47');
COMMIT;
/
CREATE TABLE ADMIN.HO_PAGETOTEM (
  ID_PAGE_TOTEM     NUMBER NOT NULL,
  TXT_NOMBRE        VARCHAR2(512 BYTE),
  NOM_CORTO         VARCHAR2(256 BYTE),
  IND_ESTADO        NUMBER(38,0),
  ARCHIVO_RUTA      VARCHAR2(256 BYTE),
  ICONO_KIND        VARCHAR2(128 BYTE),
  CONSTRAINT PK_ID_PAGE_TOTEM PRIMARY KEY(ID_PAGE_TOTEM)
);
COMMIT;
INSERT INTO ADMIN.HO_PAGETOTEM(ID_PAGE_TOTEM,TXT_NOMBRE,NOM_CORTO,IND_ESTADO,ARCHIVO_RUTA,ICONO_KIND) VALUES (1,'Administrado global permisos','admin',1,'View/test_page.xaml','HeadMinus');
INSERT INTO ADMIN.HO_PAGETOTEM(ID_PAGE_TOTEM,TXT_NOMBRE,NOM_CORTO,IND_ESTADO,ARCHIVO_RUTA,ICONO_KIND) VALUES (2,'Administrado global permisos','totem',1,'View/master_totem.xaml','ToggleSwitchVariant');
COMMIT;
/
--VENTANILLA 
CREATE TABLE ADMIN.TO_FARMVENTANILLA (
  ID_VENTANILLA   NUMBER NOT NULL,
  TXT_VENTANILLA  VARCHAR2(50 BYTE),
  IND_ESTADO      NUMBER,
  COD_EMPRESA     VARCHAR2(50 BYTE),
  IND_ZONA        NUMBER,
  ID_DEMANDA      NUMBER,
  HEX_COLOR       VARCHAR2(50 BYTE),
  CONSTRAINT PK_ID_VENTANILLA PRIMARY KEY (ID_VENTANILLA)
);
COMMIT;
INSERT INTO ADMIN.TO_FARMVENTANILLA(ID_VENTANILLA,TXT_VENTANILLA,IND_ESTADO,COD_EMPRESA,IND_ZONA,ID_DEMANDA,HEX_COLOR) VALUES (1,'VENTANILLA N° 1',1,'100',1,1,'#337ab7');
INSERT INTO ADMIN.TO_FARMVENTANILLA(ID_VENTANILLA,TXT_VENTANILLA,IND_ESTADO,COD_EMPRESA,IND_ZONA,ID_DEMANDA,HEX_COLOR) VALUES (2,'VENTANILLA N° 2',1,'100',1,1,'#eea236');
INSERT INTO ADMIN.TO_FARMVENTANILLA(ID_VENTANILLA,TXT_VENTANILLA,IND_ESTADO,COD_EMPRESA,IND_ZONA,ID_DEMANDA,HEX_COLOR) VALUES (3,'VENTANILLA N° 3',1,'100',1,1,'#87CB16');
INSERT INTO ADMIN.TO_FARMVENTANILLA(ID_VENTANILLA,TXT_VENTANILLA,IND_ESTADO,COD_EMPRESA,IND_ZONA,ID_DEMANDA,HEX_COLOR) VALUES (4,'VENTANILLA N° 4',1,'100',1,1,'#e34f49');
COMMIT;

/
--DEMANDA POR VENTANILLA 
CREATE TABLE ADMIN.TO_DEMANDAXVENTANILLA (
  ID_DEMANDA        NUMBER NOT NULL,
  ID_VENTANILLA     NUMBER,
  IND_ESTADO        NUMBER(1),
  NUM_GENERAL       NUMBER,
  NUM_PREFERENCIAL  NUMBER,
  DATE_EVENTO       DATE,
  CONSTRAINT PK_ID_DEMANDA PRIMARY KEY (ID_DEMANDA)
);
COMMIT;
INSERT INTO ADMIN.TO_DEMANDAXVENTANILLA(ID_DEMANDA,ID_VENTANILLA,IND_ESTADO,NUM_GENERAL,NUM_PREFERENCIAL,DATE_EVENTO) VALUES (1,0,1,1,2,SYSDATE);
INSERT INTO ADMIN.TO_DEMANDAXVENTANILLA(ID_DEMANDA,ID_VENTANILLA,IND_ESTADO,NUM_GENERAL,NUM_PREFERENCIAL,DATE_EVENTO) VALUES (2,1,1,1,2,SYSDATE);
INSERT INTO ADMIN.TO_DEMANDAXVENTANILLA(ID_DEMANDA,ID_VENTANILLA,IND_ESTADO,NUM_GENERAL,NUM_PREFERENCIAL,DATE_EVENTO) VALUES (3,2,1,1,2,SYSDATE);
INSERT INTO ADMIN.TO_DEMANDAXVENTANILLA(ID_DEMANDA,ID_VENTANILLA,IND_ESTADO,NUM_GENERAL,NUM_PREFERENCIAL,DATE_EVENTO) VALUES (4,3,1,1,2,SYSDATE);
COMMIT;


/
--*FALTA SECUENCUA 
CREATE SEQUENCE ADMIN.SEQ_DEMANDAXVENTANILLA
  START WITH 5
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

-- TABLA DE FILA VIRTUAL
CREATE TABLE ADMIN.TO_FILAFARMACIACENTRAL(
  ID_NUMFILA        NUMBER NOT NULL,
  COD_EMPRESA       VARCHAR2(50 BYTE),
  IND_ESTADO        NUMBER,
  TXT_SUBNUMERO     VARCHAR2(100 BYTE),
  IND_ZONA          NUMBER,
  FEC_CREACION      DATE,
  TXT_IP            VARCHAR2(50 BYTE),
  IND_PRIORIDAD     VARCHAR2(10 BYTE),
  NUM_X_DIA         NUMBER,
  DATE_CITACION     DATE,
  ID_UID            NUMBER,
  DATE_CANCELACION  DATE,
  ID_VENTANILLA     NUMBER
);
CREATE INDEX TO_FILAFARMACIACENTRAL_INDEX ON ADMIN.TO_FILAFARMACIACENTRAL (ID_NUMFILA);
CREATE SEQUENCE ADMIN.SEQ_FILAFARMACIACENTRAL
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

-- HISTORIAL DE LLAMADAS 
CREATE TABLE ADMIN.TO_HISTO_FARMVENTANILLA (
  ID_HISTOVENTANILLA  NUMBER NOT NULL,
  ID_DEMANDA          NUMBER,
  ID_VENTANILLA       NUMBER,
  IND_OPCION          NUMBER,
  DATE_EVENTO         DATE,
  ID_NUMFILA          NUMBER,
  ID_UID              NUMBER
);
CREATE INDEX TO_HISTO_FARMVENTANILLA_INDEX ON ADMIN.TO_HISTO_FARMVENTANILLA (ID_HISTOVENTANILLA);
CREATE SEQUENCE ADMIN.SEQ_HISTOVENTANILLA
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE TABLE ADMIN.TO_EVENTO_TOTEM(
  ID_EVENTO_TOTEM     NUMBER                    NOT NULL,
  ID_TOTEM            NUMBER                    NOT NULL,
  TXT_NOMBRE_EVENTO   VARCHAR2(1000 BYTE),
  IND_ESTADO          NUMBER,
  COD_RUTPRO          VARCHAR2(50 BYTE),
  DATE_INICIO_EVENTO  DATE,
  DATE_FIN_EVENTO     DATE,
  IND_PAGE            NUMBER
);
CREATE INDEX ID_EVENTO_TOTEM_INDEX ON ADMIN.TO_EVENTO_TOTEM (ID_EVENTO_TOTEM);
  
--SECUENCIA PRINCIPAL
CREATE SEQUENCE ADMIN.SEQ_EVENTO_TOTEM
  START WITH 5
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
COMMIT;
/